export const THREAD_REPOSITORY = 'THREAD_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const CATEGORY_REPOSITORY = 'CATEGORY_REPOSITORY';
export const MESSAGE_REPOSITORY = 'MESSAGE_REPOSITORY';

export const SCORING_LABEL_REPOSITORY = 'SCORING_LABEL_REPOSITORY';
export const SCORING_REPOSITORY = 'SCORING_REPOSITORY';
